utils::globalVariables(c(
  ".any", ".denom", ".strata",
  "checkbox_lbl", "checkbox_txt",
  "cv", "group_n", "label", "level_var",
  "n_level_valid", "n_strata_valid",
  "overall_lbl", "p_raw", "p_value",
  "p0", "p25", "p50", "p75", "p100",
  "pct", "pct_valid", "selected", "smd",
  "sort1", "sort2", "strata", "strata_var", 
  "group_label_first", "glue_formula",
  ".base_max_num", ".base_max_int",
  ".is_missing_level", ".is_any_selected",
  "group_id", "tbl", 
  "var_pos", "first_pos", 
  ".is_any", ".is_missing", 
  "label.from_data", "var_for_msg", "smd.y", "smd.x",
  "var_order", "level_order", ".row_in_var", "level_order2",
  "chisq_test_ht", "chisq_test_no_correction_ht", "chisq_test_simulated_ht",
  "fisher_test_ht", "fisher_test_simulated_ht",
  "num_not_miss", "is_any"
))